### ISSUE TITLE
Cheese crashes when taking picture

### ISSUE THREAD

**Issue by Zlopez** [flathub/org.gnome.Cheese#2] opened 2020-05-04 20:10 UTC
I played with cheese today and when I tried to take picture it crashed with following message:
```
May 04 22:05:31 zlopez.gamestation systemd-coredump[64339]: Process 64195 (cheese) of user 1000 dumped core.
                                                            
                                                            Stack trace of thread 2:
                                                            #0  0x00007fec4d9c1605 n/a (/usr/lib/x86_64-linux-gnu/libc-2.30.so + 0x39605)
```

How to reproduce:
1. Start Cheese
2. Take Photo

**Comment by geext-dk** [comment] 2020-05-08 17:48
I have the same issue. Happy to provide any information that could help.

**Comment by wjt** [comment] 2021-03-04 18:03
Try installing `org.gnome.Cheese.Debug`, reproducing the problem, then using [flatpak-coredumpctl](https://github.com/flatpak/flatpak/blob/master/scripts/flatpak-coredumpctl) to get a backtrace.

**Comment by alatiera** [comment] 2022-11-28 07:32
Closing due to the lack of info, please leave a comment if this is still an issue after the latest updates :)

**Closed as completed by alatiera** 2022-11-28 07:32 UTC
